diagnostic:
  appName: example-api
  publisher:
    kafka:
      bootstrap-servers: localhost:29092
      acks: all
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      compression-type: snappy
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        spring.json.trusted.packages: "*"
      topic: diagnostic-in
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diagnostic
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
#spring:
#  main:
#    allow-circular-references: true

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
